spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skincare_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    context-path: /api

spring.security:
  user:
    name: admin
    password: admin123
  csrf:
    enabled: false

jwt:
  secret: skincareServiceSecretKey2024SecureTokenGeneration
  expiration: 86400000

spring.mail:
  host: smtp.gmail.com
  port: 587
  username: skincare.service@gmail.com
  password: your-app-password
  properties:
    mail.smtp:
      auth: true
      starttls.enable: true

logging:
  level:
    org.springframework: INFO
    com.skincare: DEBUG
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

spring.thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  mode: HTML

spring.mvc:
  locale: vi_VN
  locale-resolver: fixed

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 